### ISSUE TITLE
`info.Defs[%s] == nil` panic when `go.mod` have `go 1.22`

### ISSUE THREAD

**Issue by Gyllsdorff** [nishanths/exhaustive#73]
```shell
➜ go version
go version go1.22.0 darwin/arm64
➜ exhaustive -check=switch,map ./...
panic: info.Defs[ctxKey] == nil

goroutine 7331 [running]:
github.com/nishanths/exhaustive.possibleEnumMember(0x140094ba840, 0x1400dc546e0)
	[REMOVED]/go/pkg/mod/github.com/nishanths/exhaustive@v0.12.0/enum.go:115 +0x244
➜ echo $?
2
➜ sed -i 's/go 1.22/go 1.21/g' go.mod
➜ exhaustive -check=switch,map ./...
➜ echo $?
0
```

<details>
<summary>Complete stacktrace</summary>

```shell
➜ go version
go version go1.22.0 darwin/arm64
➜ exhaustive -check=switch,map ./...
panic: info.Defs[ctxKey] == nil

goroutine 7216 [running]:
github.com/nishanths/exhaustive.possibleEnumMember(0x1400d5b0580, 0x1400d5bc820)
	[REMOVED]/go/pkg/mod/github.com/nishanths/exhaustive@v0.12.0/enum.go:115 +0x244
github.com/nishanths/exhaustive.findEnums.func1({0x1031c78f8?, 0x1400d5aa8c0?})
	[REMOVED]/go/pkg/mod/github.com/nishanths/exhaustive@v0.12.0/enum.go:76 +0x128
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0x140260b7fb0, {0x14000e98930?, 0x1?, 0x102e42e54?}, 0x14001121940)
	[REMOVED]/go/pkg/mod/golang.org/x/tools@v0.15.0/go/ast/inspector/inspector.go:82 +0x98
github.com/nishanths/exhaustive.findEnums(0x0, 0x1400d5ba060, 0x103372380?, 0x1400d5bc820)
	[REMOVED]/go/pkg/mod/github.com/nishanths/exhaustive@v0.12.0/enum.go:69 +0xa8
github.com/nishanths/exhaustive.run(0x1402d5bbad0)
	[REMOVED]/go/pkg/mod/github.com/nishanths/exhaustive@v0.12.0/exhaustive.go:111 +0x70
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0x140268f2e60)
	[REMOVED]/go/pkg/mod/golang.org/x/tools@v0.15.0/go/analysis/internal/checker/checker.go:767 +0x844
sync.(*Once).doSlow(0x140013027a8?, 0x103086904?)
	/opt/homebrew/opt/go/libexec/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
	/opt/homebrew/opt/go/libexec/src/sync/once.go:65
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(...)
	[REMOVED]/go/pkg/mod/golang.org/x/tools@v0.15.0/go/analysis/internal/checker/checker.go:683
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0x0?)
	[REMOVED]/go/pkg/mod/golang.org/x/tools@v0.15.0/go/analysis/internal/checker/checker.go:671 +0x4c
created by golang.org/x/tools/go/analysis/internal/checker.execAll in goroutine 1
	[REMOVED]/go/pkg/mod/golang.org/x/tools@v0.15.0/go/analysis/internal/checker/checker.go:677 +0x144
➜ echo $?
2
➜ sed -i 's/go 1.22/go 1.21/g' go.mod
➜ exhaustive -check=switch,map ./...
➜ echo $?
0
```
</details>

The `ctxKey` type looks like this:
```go
type ctxKeyRequestID int
const ctxKey ctxKeyRequestID = 0
```

If I change the `go.mod` file back to `go 1.21` then `exhaustive` works fine. Unfortunately I can't remove this type since it is part of the core of the service so I can't verify it other types in this service triggers the same error.

Go 1.22 includes some changes to both `go/ast` and `go/types` but I can't see anything that is the obvious source of this error. 

[Go 1.22 changelog](https://tip.golang.org/doc/go1.22#go/ast):
> [go/ast](https://tip.golang.org/pkg/go/ast/)
The following declarations related to [syntactic identifier resolution](https://pkg.go.dev/go/ast#Object) are now [deprecated](https://tip.golang.org/issue/52463): Ident.Obj, Object, Scope, File.Scope, File.Unresolved, Importer, Package, NewPackage. In general, identifiers cannot be accurately resolved without type information. Consider, for example, the identifier K in T{K: ""}: it could be the name of a local variable if T is a map type, or the name of a field if T is a struct type. New programs should use the [go/types](https://tip.golang.org/pkg/go/types) package to resolve identifiers; see [Object](https://pkg.go.dev/go/types#Object), [Info.Uses](https://pkg.go.dev/go/types#Info.Uses), and [Info.Defs](https://pkg.go.dev/go/types#Info.Defs) for details.
> [...]

**Comment by Gyllsdorff** [comment]
[Staticcheck 2023.1.7 (v0.4.7)](https://github.com/dominikh/go-tools/releases/tag/2023.1.7)
> The released binaries for this version have been built with Go 1.22 and should no longer panic when checking code targeting Go 1.22.
